# Generated by Django 5.0.4 on 2024-04-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="img",
            field=models.FileField(null=True, upload_to="icon"),
        ),
    ]
